#!/bin/bash

cd "$HOME"

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:71e6fd52/wsl-dotfile.git"

echo "Init submodules"
yadm submodule update --recursive --init
